# **Task 6**

**Q1. Arrays:** The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data. A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.

**Task:**
You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy
def arrays(arr):
    #revrse array first, convert to float array with numpy
    return(numpy.array(arr[::-1], float))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

2 4 -8 6 -3
[-3.  6. -8.  4.  2.]


**Q.2 Shape and Reshape:**

**Shape :**
The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

**Reshape:**
The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

**Task :**
You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [1]:
import numpy
A = numpy.array(input("Enter 9 space separated integers: ").strip().split(),int)
print(numpy.reshape(A,(3,3)))

Enter 9 space separated integers: 2 4 6 1 3 5 8 9 10
[[ 2  4  6]
 [ 1  3  5]
 [ 8  9 10]]


**Q3. Transpose and Flatten:**

**Transpose:** It generate the transposition of an array using the tool numpy.transpose. It won't affect the original array, but it will create a new array.

**Flatten:** The tool flatten creates a copy of the input array flattened to one dimension.

**Task:** You are given a N X M integer array matrix with space separated elements ( = rows and  = columns). Your task is to print the transpose and flatten results.


In [2]:
import numpy

n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 3
1 8
6 9
[[1 6]
 [8 9]]
[1 8 6 9]


**Q4. Concatenate:** 

**Task:** You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [3]:
import numpy as np
N, M, P = map(int,input().split())
array_A = np.array([input("Enter elements for Array A: ").split() for _ in range(N)],int)
array_B = np.array([input("Enter elements for Array B: ").split() for _ in range(M)],int)
print(np.concatenate((array_A, array_B), axis = 0))


3 2 4
Enter elements for Array A: 1 2
Enter elements for Array A: 2 3
Enter elements for Array A: 2 1
Enter elements for Array B: 1 3
Enter elements for Array B: 2 3
[[1 2]
 [2 3]
 [2 1]
 [1 3]
 [2 3]]


**Q5.Zeros and Ones:** 

**zeros:** The zeros tool returns a new array with a given shape and type filled with 0's.

**ones:** The ones tool returns a new array with a given shape and type filled with 1's.

**Task:**You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [7]:
import numpy
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

2 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**Q6. Eye and Identity:**

**Identity:** The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as 1 and the rest as 0. The default type of elements is float.

**Eye:** The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter K. A positive K is for the upper diagonal, a negative K is for the lower, and a 0 K (default) is for the main diagonal.

**Task:** Your task is to print an array of size N*M with its main diagonal elements as 1's and 0's everywhere else.

In [9]:
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)

5 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


**Q7. Array Mathematics:** Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

**Task:**You are given two integer arrays, and of dimensions X. Your task is to perform the following operations: Add ( + ) Subtract ( - ) Multiply ( * ) Integer Division ( / ) Mod ( % ) Power ( ** )

In [11]:
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")


1 5
1 2 3 4 5
5 6 7 8 9
[[ 6  8 10 12 14]]
[[-4 -4 -4 -4 -4]]
[[ 5 12 21 32 45]]
[[0 0 0 0 0]]
[[1 2 3 4 5]]
[[      1      64    2187   65536 1953125]]


**Q8. Floor, Ceil and Rint:** 
Given a 1-D array, A . Your task is to print the floor, ceil and rint of all the elements of A.

In [12]:
numpy.set_printoptions(legacy = '1.13')
a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))  


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


**Q9. Sum and Prod:**
You are given a 2-D array with dimensions NXM.
Your task is to perform the sum tool over axis 0 and then find the product of that result. 


In [14]:
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))


2 2
3 2
2 5
35


**Q.10 Min and Max:** You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 1 and then find the max of that.

In [17]:
arr=[]
n,m=map(int,input().split())
for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)
my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)
print(max(result))


4 2
9 1
2 5
8 6
3 7
6


**Q11.Mean, Var, and Std:**

Mean: The mean tool computes the arithmetic mean along the specified axis.
Variance: The var tool computes the arithmetic variance along the specified axis.
Std: The std tool computes the arithmetic standard deviation along the specified axis.

**Task:** You are given a 2-D array of size X.
Your task is to find:

The mean along axis
The var along axis
The std along axis

In [18]:
N,M = map(int,input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(A.mean(axis=1))
print(A.var(axis=0))
print(A.std())

2 2
3 5
4 2
[ 4.  3.]
[ 0.25  2.25]
1.11803398875


**Q12. Dot and Cross:** You are given two arrays A and B. Both have dimensions of X.

Your task is to compute their matrix product.

In [19]:
N = int(input())
A = numpy.array([input("Enter for Array A: ").split() for i in range(N)], dtype =int)
B = numpy.array([input("Enter for Array B: ").split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)

2
Enter for Array A: 2 6
Enter for Array A: 5 1
Enter for Array B: 3 4
Enter for Array B: 2 8
[[18 56]
 [17 28]]


**Q13.Inner and Outer:**
You are given two arrays: and . Your task is to compute their inner and outer product.

In [21]:
a = numpy.array(input("Enter for Array A: ").split() , int)
b = numpy.array(input("Enter for Array B: ").split() , int)
print("------------Inner Product---------------")
print(numpy.inner(a, b))
print("------------Outer Product---------------")
print(numpy.outer(a, b))


Enter for Array A: 0 1
Enter for Array B: 4 5
------------Inner Product---------------
5
------------Outer Product---------------
[[0 0]
 [4 5]]


**Q14. Polynomials:** You are given the coefficients of a polynomial P. Your task is to find the value of P at point x.

In [22]:
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))

1.2 2 3.1
1
6.3


**Q15. Linear Algebra:**
You are given a square matrix A with dimensions N X N . Your task is to find the determinant.

In [28]:
numpy.set_printoptions(legacy='1.13')
N = int(input())
A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))

2
3.4 2.5
2.3 5.1
11.59


In [ ]:
 6